[package]
name = "demo-things"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
webthing = "0.15.0"
serde_json = "1.0"
uuid = { version = "0.8", features = ["v4"] }
actix-rt = "2.6"
env_logger = "0.9"
