[package]
name = "demo-things"
version = "0.1.0"
edition = "2021"

[dependencies]
serde_json = "1.0"
uuid = { version = "1.1.1", features = ["v4", "serde"] }
wot-td = { git = "https://github.com/sifis-home/wot-rust" }
axum = "0.5.6"
tokio = { version = "1.18.2", features = ["macros", "time"] }
tracing-subscriber = { version = "0.3.11", features = ["fmt"] }
tracing = "0.1.34"
once_cell = "1.12.0"
serde = { version = "1.0.137", features = ["rc", "derive"] }
bytes = "1.1.0"
time = { version = "0.3.9", features = ["serde", "serde-well-known"] }

[features]
